[package]
name = "actix-web-cron-example"
version = "0.1.0"
authors = ["Patrick Fitzgerald <paddyfitz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# actix
actix = "^0.9"
actix-web-actors = "^2.0"
actix-web = "2.0.0"
actix-rt = "1.1.1"

serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"